use bundlesize to ensure bundle does not exceed certain thresholds
solid/mashlib pull request #101
Opened 2020-08-23 16:39 UTC by angelo-v

2020-08-23 16:40 UTC, angelo-v commented on package.json
> +    "prepublishOnly": "npm test && npm run build && npm run bundlesize",
Shouldn't `npm run build-dist` run here by the way? (Instead of `npm run build` which included the dev build)

2020-08-24 07:48 UTC, michielbdejong commented on package.json
> +    "prepublishOnly": "npm test && npm run build && npm run bundlesize",
Looking at https://github.com/solid/mashlib/blob/master/package.json#L11 I think `npm run build` does run:
* npm run clean
* npm run build-version 
* npm run build-dev 
* npm run build-dist

I think we do need the first two before publishing an npm version. Are you saying skip the third step?

2020-08-24 07:50 UTC, michielbdejong commented
I agree with adding the `bundlesize` command but maybe not with failing the release if it's bigger than 1Mb. What should we do when (in the middle of doing a release) the library turns out to be too big? What is its size now?

2020-08-24 07:50 UTC, michielbdejong requested changes
Maybe just add the command but not make it block the release?

2020-08-24 15:27 UTC, angelo-v commented on package.json
> +    "prepublishOnly": "npm test && npm run build && npm run bundlesize",
At least build-dev could be skipped I guess, but let's tackle this in a separate task

2020-08-24 15:32 UTC, angelo-v commented
> Maybe just add the command but not make it block the release?

I think it is actually important that it breaks the build, otherwise it will not be regarded.

If it does, we have to options:

 1. Check what caused it and resolve it as far as possible
 2. Deliberatly choose to increase the threshold

I find a deliberate decision very important and want to prevent making the bundle bigger and bigger without noticing directly.

The bundlesize check is included in github, there you can see the current size and limit:

![image](https://user-images.githubusercontent.com/340725/91064614-c1f2fd00-e62f-11ea-963a-9ccebd60577d.png)

2020-08-24 15:34 UTC, angelo-v commented
PS: Since it is checked on travis as well, it will not fail in the middle of a release but already in the PR that causes the bundle to exceed size

2020-08-25 07:49 UTC, michielbdejong commented
Still, it will fail in mashlib and not in solid-panes or in the pane in question or in solid-ui. Mashlib is an almost empty shell around solid-panes, we only do mashlib PRs to include the latest solid-panes master. But I agree with your reasoning and I guess it's better than nothing. Let's discuss it in tomorrow's Solid OS meeting (every Wednesday 13:00 CEST in https://meet.jit.si/solid-operating-system). Maybe we can also do other things (lazy loading?) that reduce the size.

2020-08-25 14:04 UTC, angelo-v commented
The check is in mashlib, because mashlib is what bundles everything up. We cannot include it in the other repos, because we have no bundles there we could measure. I can analyse the bundle to see which dependencies cause the size and do something about it. We can also see how it works out in practise and relax the check if it disturbs more than it helps.

2020-08-27 06:47 UTC, angelo-v commented
@michielbdejong so can we merge this as discussed?

2020-08-28 12:16 UTC, michielbdejong approved these changes
Yes, go ahead and merge, as discussed in the Solid OS meeting.

2020-08-28 16:07 UTC, merged